version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing source NPM dependencies...
      - echo update npm...
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - yarn install
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - yarn run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Distributing to S3...
artifacts:
  files:
    - "**/*"
  base-directory: "dist*"
  discard-paths: no
